FROM --platform=linux/amd64 node:latest

WORKDIR /app

COPY . .

RUN npm install --legacy-peer-deps

RUN npm run build:ssr

WORKDIR /app/packages/ssr-proj

COPY packages/ssr-proj ./


EXPOSE 3000

CMD [ "npm", "run", "start" ]

FROM --platform=linux/amd64 nginx:latest
COPY nginx.conf /etc/nginx/nginx.conf
RUN mkdir -p /etc/nginx/ssl

