name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALI_HUB_USR_NAME }}
          password: ${{ secrets.ALI_HUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: registry.cn-hangzhou.aliyuncs.com/jim_hub/poetry_frontend:latest
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ALIYUN_HOST }}
          username: ${{ secrets.ALIYUN_USER_NAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
          script: |
            docker stop poetry_frotend
            docker rm poetry_frotend
            docker pull registry.cn-hangzhou.aliyuncs.com/jim_hub/poetry_frontend:latest 
            docker run -d -p 80:80 --name poetry_frotend  \ -v /usr/local/nginx/ssl/www.jimvivenbridge.fun.key:/etc/nginx/ssl/www.jimvivenbridge.fun.key \ -v /usr/local/nginx/ssl/www.jimvivenbridge.fun.pem:/etc/nginx/ssl/www.jimvivenbridge.fun.pem \ registry.cn-hangzhou.aliyuncs.com/jim_hub/poetry_frontend:latest
